---
title: "brms analysis"
output: html_document
date: "2025-09-20"
---

```{r }
##############################################################################
#-------------------------------  Preparation -------------------------------#
##############################################################################
library(tidyverse)
library(stringr)
library(brms)
library(ggthemes)
library(cowplot)
library(tidybayes)

library(coda)

estimate_mode <- function(s) {
  d <- density(s)
  return(d$x[which.max(d$y)])
}

hdi_upper<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","upper"])
}

hdi_lower<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","lower"])
}

```


```{r }

# Combine datasets from two waves
# --> Restructure_data.R --> saves combined long-format dataset in file "laac_complete.txt"
#long <- read.csv("laac_complete.txt", sep="", na.strings="-99")

long <- read.csv("../data/laac_complete.txt", sep="", na.strings="-99")

# create categorical variables indicating time point and stable trait level
long$trial <- as.factor(long$trial)
long$time_cat <- as.factor(long$time_point)
long$trait <- 1
# recode search task to binary response
long[long$task == "search", "code"] <- car::recode(long[long$task == "search", "code"], '2=1')

long_bin <- long%>%
  filter(!is.na(code))%>%
  group_by(time_point, subject, task, time_cat, trait)%>%
  summarise(n = length(code), 
            sum = sum(code))%>%
  ungroup()

long_bin_all <- long_bin%>%
  mutate(phase = ifelse(task %in% c("cause", "delay", "gaze", "inference", "quant"), 1, 2))%>%
  mutate(time_point = ifelse(phase == 1, time_point - 4, time_point))%>%
  filter(time_point > 0)%>%
  mutate(time_cat = as.factor(time_point))


table(long_bin_all$subject,long_bin_all$task)
```

```{r }
##############################################################################
#---------------------- Estimate Rasch models using brms --------------------#
##############################################################################

# Select task to be modeled (for single-task models only)
# here: visible food
task <- long %>%
  filter(str_detect(task, 'food'))

######################## Ignore visible food
# Latent State model
state <-  brm(code ~ 0 + time_cat + trial + (0 + time_cat | subject),
                 data = task,
                 family = brmsfamily(family="bernoulli", link="logit"),
                 chains = 3, # to speed up sampling --> increase later
                  cores = 3,
                 iter=4000)

saveRDS(state, "../saves/ls_rasch.rds")
state <- readRDS("../saves/ls_rasch.rds")

# Latent State Trait model
LST <-  brm(code ~ 0 + time_cat + trial + (0 + time_cat || subject) + (0 + trait | subject),
                 data = task,
                 family = brmsfamily(family="bernoulli", link="logit"),
                 chains = 3, # to speed up sampling --> increase later
                  cores = 3,
                 iter=4000)
saveRDS(LST, "../saves/lst_rasch.rds")

LST <- readRDS("../saves/lst_rasch.rds")

# Latent Growth Curve model
LGC <-  brm(code ~ 0 + time_point + trial + (1 + time_point | subject),
                 data = task,
                 family = brmsfamily(family="bernoulli", link="logit"),
                 chains = 3, # to speed up sampling --> increase later
                  cores = 3,
                 iter=2000)

saveRDS(LGC, "../saves/lgc_rasch.rds")

LGC <- readRDS("../saves/lgc_rasch.rds")



```

```{r}
##### Inspect results
plot(state) # check convergence / traceplots; insert respective model
pp_check(state)
```


```{r}
## Latent state model
results <- summary(state)
# Latent state "means" (varying easiness across time) and trial easiness parameters
results$fixed
# latent state correlations across time
results$random$subject[11:55,]
# plot probabilities of correct responses per time point
# (these correspond to prob. of first trial per time point)
conditional_effects(state, "time_cat")
# pattern of probabilities across trials
conditional_effects(state, "trial")

## LST model
results <- summary(LST)
# Compute consistency coefficients (these vary across time points)
con <- results$random$subject[11,1] / ( results$random$subject[11,1] + results$random$subject[,1] )

## LGC model
# Is there a linear trend over time?
results <- summary(LGC)
results$fixed["time_point",]
```

```{r}
cor <- results$random$subject[11:55,]%>%as_tibble(rownames = "cor")%>%
  mutate(cor = str_remove(cor, "cor\\(time_cat"),
         cor = str_remove(cor, "\\)"),
         cor = str_remove(cor, "time_cat"))%>%
  tidyr::separate(cor, sep = ",", into = c("a", "b"))%>%
  mutate(a = as.numeric(a), 
         b = as.numeric(b))
```

```{r}

# Latent state correlations rasch model
state_means_rasch <- tibble()
cor_rasch <- tibble()

for (i in c("pop", "reas" , "comm", "vfood", "search", "attent" )) {
  
  task <- long %>%filter(task == i)
  
  state <-  brm(code ~ 0 + time_cat + trial + (0 + time_cat | subject),
                 data = task,
                 family = brmsfamily(family="bernoulli", link="logit"),
                 chains = 3, # to speed up sampling --> increase later
                 cores = 3,
                 #threads = threading(8),
                 backend = "cmdstanr",
                 iter=3000)
  
  
  results <- summary(state)
  
  state_means <- results$fixed%>%as_tibble(rownames = "time_point")%>%filter(grepl("time_cat", time_point))%>%mutate(task = i)
  
  state_means_rasch <- bind_state_means_rasch(state_means_rasch, state_means)
  
  cor_state <- results$random$subject[11:55,]%>%as_tibble(rownames = "cor")%>%
  mutate(cor = str_remove(cor, "cor\\(time_cat"),
         cor = str_remove(cor, "\\)"),
         cor = str_remove(cor, "time_cat"))%>%
  tidyr::separate(cor, sep = ",", into = c("a", "b"))%>%
  mutate(a = as.numeric(a), 
         b = as.numeric(b))%>%
    mutate(task = i)
  
  cor_rasch <- bind_rows(cor_rasch, cor_state)
  
}

saveRDS(cor_rasch, "../saves/latent_state_cor_rasch.rds")
saveRDS(state_means_rasch, "../saves/latent_state_means_rasch.rds")


```


```{r}
plsc_rasch <- cor_rasch%>%
  mutate(task = factor(task, levels = c("attent",  "comm", "vfood", "pop", "reas","search")))%>%
  ggplot(aes(y = factor(b), x = factor(a), fill = Estimate))+
    geom_tile(color = "white")+
  labs(x = "", y = "")+
  scale_fill_gradientn(
    colors = c("darkgrey","darkgrey", "#CC6677", "#FFE066", "#117733"),  # Define four colors
    values = scales::rescale(c(-0.1,0, 0.01, 0.5, 1)),  # Define the position of the points along the scale
    limits = c(-0.1, 1),  # Ensure values match your data range
    space = "Lab", 
    name = "Correlation",
    breaks = c(0, 0.5, 1)
  ) +
  geom_text(aes(label = round(Estimate, 2)), size = 2)+
  scale_y_discrete(breaks = c(2,10))+
  scale_x_discrete(breaks = c(1,9))+
  facet_wrap(~task, nrow = 1)+
  theme_few()+
  theme(legend.position = c(0.975,0.25), legend.direction = "vertical", legend.title = element_blank(), legend.background = element_blank(), 
        #strip.text = element_blank(),
        legend.text = element_text(size = 8), legend.key.size = unit(0.4, "cm"))
```
```{r }
plot_grid(plsc_rasch, plsc2, align = "v",axis = "l", rel_heights = c(1,1), ncol = 1)
```

```{r}
ggsave("../visuals/ls_comp_rasch.png", height = 6, width = 14, scale = 0.9)
```

# Latent state correlations binomial

```{r}

# Latent state correlations rasch model

cor_bin <- tibble()

for (i in c("pop", "reas" , "comm", "vfood", "search", "attent" )) {
  
  task <- long_bin %>%
    filter(!subject %in% c("frank", "hodari"))%>%
    filter(task == i)
  
  state <-  brm(sum|trials(n) ~ 0 + time_cat + (0 + time_cat | subject),
                 data = task,
                 family = binomial(),
                 chains = 4, # to speed up sampling --> increase later
                 cores = 4,
                 threads = threading(8),
                 backend = "cmdstanr",
                 iter=4000)
  
  
  results <- summary(state)
  
  cor_state <- results$random$subject[11:55,]%>%as_tibble(rownames = "cor")%>%
  mutate(cor = str_remove(cor, "cor\\(time_cat"),
         cor = str_remove(cor, "\\)"),
         cor = str_remove(cor, "time_cat"))%>%
  tidyr::separate(cor, sep = ",", into = c("a", "b"))%>%
  mutate(a = as.numeric(a), 
         b = as.numeric(b))%>%
    mutate(task = i)
  
  cor_bin <- bind_rows(cor_bin, cor_state)
  
}

saveRDS(cor_bin, "../saves/ls_cor_bin_ex_infants.rds")

cor_bin <- readRDS("../saves/ls_cor_bin.rds")
cor_bin_ex_inf <- readRDS("../saves/ls_cor_bin_ex_infants.rds")

```

## For individual timepoints to avoid shrinkage 

```{r}
# pairwise_recur <- function(n, start = 1) {
#   if (n == start) return()
#   nrows <- factorial(n) / (factorial(2) * factorial(n-2))
#   res <- matrix(nrow = nrows, ncol = 2)
#   rbind(
#     cbind(rep(start, times = n - start),
#           1 + start:(n-1)),
#     pairwise_recur(n, start = start + 1)
#   )
# }
# 
# x <- pairwise_recur(10)
# 
# pairs <- x%>%as_tibble()%>%rowwise()%>%mutate(pair = pmap(list(V1, V2), c))%>%pull(pair)

cor_rasch_ind_tp <- tibble()

test_lsc <- long %>%filter(task == "vfood")

for (i in pairs) {
  
  tpd <- test_lsc %>%filter(time_point %in% unlist(i))
  
  state <-  brm(code ~ 0 + time_cat + trial + (0 + time_cat | subject),
                 data = tpd,
                 family = brmsfamily(family="bernoulli", link="logit"),
                 chains = 3, # to speed up sampling --> increase later
                 cores = 3,
                 #threads = threading(8),
                 #backend = "cmdstanr",
                 iter=3000)
  
  results <- summary(state)
  
  cor_state <- results$random$subject%>%as_tibble(rownames = "cor")%>%
  filter(grepl("cor", cor))%>%
  mutate(cor = str_remove(cor, "cor\\(time_cat"),
         cor = str_remove(cor, "\\)"),
         cor = str_remove(cor, "time_cat"))%>%
  tidyr::separate(cor, sep = ",", into = c("a", "b"))%>%
  mutate(a = as.numeric(a), 
         b = as.numeric(b))
  
  cor_rasch_ind_tp <- bind_rows(cor_rasch_ind_tp, cor_state)
  
}

saveRDS(cor_rasch_ind_tp, "../saves/cor_rasch_ind_tp.rds")

```



```{r}
plsc_bin_2 <- cor_bin%>%
  filter(task == "vfood")%>%
  #mutate(task = factor(task, levels = c("attent",  "comm", "vfood", "pop", "reas","search")))%>%
  ggplot(aes(y = factor(b), x = factor(a), fill = Estimate))+
    geom_tile(color = "white")+
  labs(x = "", y = "")+
  scale_fill_gradientn(
    colors = c("darkgrey","darkgrey", "#CC6677", "#FFE066", "#117733"),  # Define four colors
    values = scales::rescale(c(-0.1,0, 0.01, 0.5, 1)),  # Define the position of the points along the scale
    limits = c(-0.1, 1),  # Ensure values match your data range
    space = "Lab", 
    name = "Correlation",
    breaks = c(0, 0.5, 1)
  ) +
  geom_text(aes(label = round(Estimate, 2)), size = 2)+
  scale_y_discrete(breaks = c(2,10), limits=rev)+
  scale_x_discrete(breaks = c(1,9))+
  #facet_wrap(~task, nrow = 1)+
  ggtitle("All tp Rasch")+
  theme_few()+
  theme(legend.position = c(0.975,0.25), legend.direction = "vertical", legend.title = element_blank(), legend.background = element_blank(), 
        #strip.text = element_blank(),
        legend.text = element_text(size = 8), legend.key.size = unit(0.4, "cm"))
```

```{r }
plot_grid(plsc_bin, plsc,plsc_bin_2, align = "v",axis = "l", rel_heights = c(1,1,1), ncol = 1)
```

```{r}
ggsave("../visuals/ls_comp_ind.pdf", height = 14, width = 8, scale = 0.9)
```

# Multi-task LSTMs Rasch

```{r}
####################################################################################
#----------  Estimate "multidimenensional" Rasch models for several tasks ----------
####################################################################################

# Latent Trait model (ignore state variability)
# (makes unrealistic assumption of perfectly stable inter-inidividual differences across time)
Multi_Trait <-  brm(code ~ 0 + time_cat + trial + task + time_cat:task + trial:task
                  + (0 + task | subject),
                  data = long,
                  family = brmsfamily(family="bernoulli", link="logit"),
                  chains = 2,
                  iter=1000) # decreased for model testing
summary(Multi_Trait)

# Latent State Trait model

# test LST model for combination of two tasks only
# --> combining all tasks needs VERY long estimation times --> habe ich erstmal abgebrochen
test <- long[long$task %in% c("pop","attent","inference"),]
Multi_LST2 <-  brm(code ~ 0 + time_cat + trial + task + time_cat:task + trial:task
                  + (0 + time_cat + time_cat:task || subject) + (0 + task | subject),
            data = test,
            family = brmsfamily(family="bernoulli", link="logit"),
                 chains = 4, # to speed up sampling --> increase later
                  cores = 4,
            backend = "cmdstanr",
            threads = threading(10),
            iter=4000) # decreased for model testing
summary(Multi_LST2)

saveRDS(Multi_LST, "../saves/multi_lst_cause_food_delay.rds")
saveRDS(Multi_LST2, "../saves/multi_pop_att_food_inf.rds")
```


```{r}
Multi_LST <- readRDS("../saves/multi_lst1.rds")
Multi_LST2 <- readRDS("../saves/multi_lst2.rds")

sum_mult <- summary(Multi_LST)
sum_mult2 <- summary(Multi_LST2)
```


```{r}
get_variables(Multi_LST)

```

## Consistencies

```{r}
# rasch
con_samp_raw <- posterior_samples(Multi_LST2, pars = "^sd_subject", add_chain = T)%>%
  sample_n(5000)%>%
  pivot_longer(names_to = "param", values_to = "value", cols = -c(chain, iter))

con_samp <- con_samp_raw%>%
  mutate(t = str_remove(param, "sd_subject\\__"),
         t = str_remove(t, "task"))%>%
  separate(t, into = c("tp", "task"), sep = "\\:")%>%
  filter(grepl("cat", tp))%>%
  mutate(task = ifelse(is.na(task), "attent", task),
         time_point = str_remove(tp, "time_cat"),
         tp_samp = value)%>%
  select(task, time_point, tp_samp, chain, iter)%>%
  left_join(
    con_samp_raw%>%
    filter(!grepl("time_cat", param))%>%
    mutate(task = str_remove(param, "sd_subject\\__task"))%>%
    mutate(trait_samp = value)%>%
    select(task, trait_samp, chain, iter)
  )%>%
  rowwise()%>%
  mutate(
    con = trait_samp / (trait_samp+tp_samp)
  )


con_sum <- con_samp%>%
  group_by(task)%>%
  summarise(con_m = estimate_mode(con), 
            con_lci = hdi_lower(con), 
            con_uci = hdi_upper(con))

saveRDS(con_sum, "../saves/consistency_sample.rds")

con_sum <- readRDS("../saves/consistency_sample.rds")

# binomial
con_samp_raw_bin <- posterior_samples(Multi_LST2_bin, pars = "^sd_subject", add_chain = T)%>%
  sample_n(5000)%>%
  pivot_longer(names_to = "param", values_to = "value", cols = -c(chain, iter))

con_samp_bin <- con_samp_raw_bin%>%
  mutate(t = str_remove(param, "sd_subject\\__"),
         t = str_remove(t, "task"))%>%
  separate(t, into = c("tp", "task"), sep = "\\:")%>%
  filter(grepl("cat", tp))%>%
  mutate(task = ifelse(is.na(task), "attent", task),
         time_point = str_remove(tp, "time_cat"),
         tp_samp = value)%>%
  select(task, time_point, tp_samp, chain, iter)%>%
  left_join(
    con_samp_raw_bin%>%
    filter(!grepl("time_cat", param))%>%
    mutate(task = str_remove(param, "sd_subject\\__task"))%>%
    mutate(trait_samp = value)%>%
    select(task, trait_samp, chain, iter)
  )%>%
  rowwise()%>%
  mutate(
    con = trait_samp / (trait_samp+tp_samp)
  )


con_sum_bin <- con_samp_bin%>%
  group_by(task)%>%
  summarise(con_m = estimate_mode(con), 
            con_lci = hdi_lower(con), 
            con_uci = hdi_upper(con))

saveRDS(con_sum_bin, "../saves/consistency_bin_sample.rds")

con_sum_bin <- readRDS("../saves/consistency_bin_sample.rds")
```

#### Compare methods 

```{r}
bind_rows(
lstv_con_rel%>%filter(param == "consistency", !grepl("7", task))%>%mutate(type ="mplus_sem")%>%
  select(-param)%>%
  dplyr::rename(con_lci = lower_2.5ci,
                con_uci = upper_2.5ci, 
                con_m = value)%>%
  mutate(
      task = recode(task,
       "pop-to-sample" = "Population-to-sample",
       "communication" = "Communicative-cues",
       "reasoning" = "Probabilistic-reasoning",
       "visible-food" = "Ignore-visible-food",
       "inhibit-searched" = "Self-ordered-search",
       "attention" = "Attention-following")
  ),

con_sum%>%mutate(
  type ="brms_rasch",
  task = recode(task,
       "pop" = "Population-to-sample",
       "comm" = "Communicative-cues",
       "reas" = "Probabilistic-reasoning",
       "vfood" = "Ignore-visible-food",
       "search" = "Self-ordered-search",
       "attent" = "Attention-following")
   )#,
# 
# con_sum_bin%>%mutate(
#   type ="brms_rasch",
#   task = recode(task,
#        "pop" = "Population-to-sample",
#        "comm" = "Communicative-cues",
#        "reas" = "Probabilistic-reasoning",
#        "vfood" = "Ignore-visible-food",
#        "search" = "Self-ordered-search",
#        "attent" = "Attention-following")
#   )
)%>%
  ggplot(aes(x = task, y = con_m))+
  geom_pointrange(aes(ymin= con_lci, ymax = con_uci, col = type), position = position_dodge(width = 0.2))+
  theme_few()+
  ylim(0,1)+
  labs(x = "", y = "LST model estimate")+
  scale_color_colorblind(name = "")+
  theme(legend.direction = "vertical", legend.position = c(0.2, 0.25), legend.box = "horizontal", legend.background = element_blank()
    )+
  ggtitle("Consistencies across methods")
```
```{r}
ggsave("../visuals/con_comp.png",width = 8, height = 3, scale = 1.5)
```


## Correlations between tasks

```{r}
cor_mult <- bind_rows(
  sum_mult$random$subject%>%as_tibble(rownames = "param"),
  sum_mult2$random$subject%>%as_tibble(rownames = "param")
  )%>%
  filter(grepl("cor\\(", param))%>%
    mutate(param = str_remove(param, "cor\\("),
         param = str_remove(param, "\\)"),
         param = str_remove_all(param, "task"))%>%
  tidyr::separate(param, sep = ",", into = c("a", "b"))%>%
  mutate(Estimate = ifelse(a == "search" | b == "search", Estimate*-1, Estimate))%>%
  mutate(b = recode(b,
    attent = "ZAttention-following",
    gaze = "ZGaze-following",
    cause = "Causal-inference",
    inference = "Inference-by-exclusion",
    delay = "Delay-of-gratification",
    comm = "ZCommunicative-cues",
    search = "Self-ordered-search",
    pop = "Population-to-sample",
    quant = "Quantity-discrimination",
    reas = "XProbabilistic-reasoning",
    vfood = "Ignore-visible-food"
  ),
  a = recode(a,
    attent = "ZAttention-following",
    gaze = "ZGaze-following",
    cause = "Causal-inference",
    inference = "Inference-by-exclusion",
    delay = "Delay-of-gratification",
    comm = "ZCommunicative-cues",
    search = "Self-ordered-search",
    pop = "Population-to-sample",
    quant = "Quantity-discrimination",
    reas = "XProbabilistic-reasoning",
    vfood = "Ignore-visible-food"
  ))%>%
   rowwise()%>%
  mutate(id = paste(sort(c(b, a)), collapse = "_"))%>%
  separate(id, into = c("task", "task_1"), sep = "_")%>%
  add_row(task_1 = "Ignore-visible-food", task = "Ignore-visible-food", Estimate = 0)%>%
   add_row(task = "ZCommunicative-cues",task_1 = "ZCommunicative-cues", Estimate = 0)%>%
  arrange(task, task_1)%>%
  mutate(
    zero = 0, 
    sig = ifelse(between(zero, `l-95% CI`, `u-95% CI`), "plain", "bold"),
    sig = ifelse(is.na(sig), "plain", sig))%>%
  mutate(order = as.numeric(factor(task)),
         order_1 = as.numeric(factor(task_1)))

saveRDS(cor_mult, "../saves/cor_mult.rds")

cor_mult <- readRDS("../saves/cor_mult.rds")
```

```{r}
p_cor_rasch <- cor_mult%>%
  ggplot(aes(y = factor(order), x = factor(order_1), fill = Estimate))+
  geom_tile(color = "white")+
  labs(x = "", y = "")+
  scale_fill_gradient2(low = "#CC6677", high = "#117733", mid = "white", 
  midpoint = 0, limit = c(-1,1), space = "Lab", 
  name="Correlation")+
  #ggtitle("Model based correlations")+
  geom_text(aes(label = round(Estimate, 2), fontface = sig), size = 3)+
  scale_y_discrete(breaks = c(1:10),labels = c(str_remove(str_remove(sort(unique(cor_mult$task)), "Z"),"X")))+
  scale_x_discrete(guide = guide_axis(angle = 90), labels = c(str_remove(str_remove(sort(unique(cor_mult$task_1)), "Z"),"X")))+
  #scale_y_discrete(limits=rev, breaks = c(1:10))+
  #scale_x_discrete(breaks = c(1:9))+
  theme_few()+
  theme(legend.position =  c(0.15, 0.8), legend.direction = "vertical", legend.title = element_blank(), legend.background = element_blank())
```

```{r}
plot_grid(pcor_mod_a, p_cor_rasch)
```

```{r}
ggsave("../visuals/cor_comp.pdf",width = 14, height = 6, scale = 1)
```


# Multi-task LSTMs Binomial

```{r}
Multi_LST_bin <- readRDS("../saves/multi_lst_bin.rds")
Multi_LST1_bin <- readRDS("../saves/multi_lst1_bin.rds")
Multi_LST2_bin <- readRDS("../saves/multi_lst2_bin.rds")

sum_mult_bin <- summary(Multi_LST_bin)
sum_mult1_bin <- summary(Multi_LST1_bin)
sum_mult2_bin <- summary(Multi_LST2_bin)
```

## Correlations between tasks

```{r}
cor_mult_bin <- sum_mult_bin$random$subject%>%as_tibble(rownames = "param")%>%
  filter(grepl("cor\\(", param))%>%
    mutate(param = str_remove(param, "cor\\("),
         param = str_remove(param, "\\)"),
         param = str_remove_all(param, "task"))%>%
  tidyr::separate(param, sep = ",", into = c("a", "b"))%>%
  mutate(Estimate = ifelse(a == "search" | b == "search", Estimate*-1, Estimate))%>%
  mutate(b = recode(b,
    attent = "ZAttention-following",
    gaze = "ZGaze-following",
    cause = "Causal-inference",
    inference = "Inference-by-exclusion",
    delay = "Delay-of-gratification",
    comm = "ZCommunicative-cues",
    search = "Self-ordered-search",
    pop = "Population-to-sample",
    quant = "Quantity-discrimination",
    reas = "XProbabilistic-reasoning",
    vfood = "Ignore-visible-food"
  ),
  a = recode(a,
    attent = "ZAttention-following",
    gaze = "ZGaze-following",
    cause = "Causal-inference",
    inference = "Inference-by-exclusion",
    delay = "Delay-of-gratification",
    comm = "ZCommunicative-cues",
    search = "Self-ordered-search",
    pop = "Population-to-sample",
    quant = "Quantity-discrimination",
    reas = "XProbabilistic-reasoning",
    vfood = "Ignore-visible-food"
  ))%>%
   rowwise()%>%
  mutate(id = paste(sort(c(b, a)), collapse = "_"))%>%
  separate(id, into = c("task", "task_1"), sep = "_")%>%
  add_row(task_1 = "Ignore-visible-food", task = "Ignore-visible-food", Estimate = 0)%>%
   add_row(task = "ZCommunicative-cues",task_1 = "ZCommunicative-cues", Estimate = 0)%>%
  arrange(task, task_1)%>%
  mutate(
    zero = 0, 
    sig = ifelse(between(zero, `l-95% CI`, `u-95% CI`), "plain", "bold"),
    sig = ifelse(is.na(sig), "plain", sig))%>%
  mutate(order = as.numeric(factor(task)),
         order_1 = as.numeric(factor(task_1)))

saveRDS(cor_mult_bin, "../saves/cor_mult_bin.rds")

cor_mult_bin <- readRDS("../saves/cor_mult_bin.rds")
```

```{r}
p_cor_bin <- cor_mult_bin%>%
  ggplot(aes(y = factor(order), x = factor(order_1), fill = Estimate))+
  geom_tile(color = "white")+
  labs(x = "", y = "")+
  scale_fill_gradient2(low = "#CC6677", high = "#117733", mid = "white", 
  midpoint = 0, limit = c(-1,1), space = "Lab", 
  name="Correlation")+
  ggtitle("brms binomial model")+
  geom_text(aes(label = round(Estimate, 2), fontface = sig), size = 3)+
  scale_y_discrete(breaks = c(1:10),labels = c(str_remove(str_remove(sort(unique(cor_mult_bin$task)), "Z"),"X")))+
  scale_x_discrete(guide = guide_axis(angle = 90), labels = c(str_remove(str_remove(sort(unique(cor_mult_bin$task_1)), "Z"),"X")))+
  #scale_y_discrete(limits=rev, breaks = c(1:10))+
  #scale_x_discrete(breaks = c(1:9))+
  theme_few()+
  theme(legend.position =  c(0.15, 0.8), legend.direction = "vertical", legend.title = element_blank(), legend.background = element_blank())
```

```{r}
plot_grid(p_cor_bin, pcor_mod_a)
```

```{r}
ggsave("../visuals/cor_comp_bin.pdf",width = 14, height = 6, scale = 1)
```

## Pairwise correlations between tasks

```{r}
pair_cor_mult_bin <- readRDS("../saves/pairwise_multi_lst_bin.rds")%>%
    mutate(param = str_remove(param, "cor\\("),
         param = str_remove(param, "\\)"),
         param = str_remove_all(param, "task"))%>%
  tidyr::separate(param, sep = ",", into = c("a", "b"))%>%
  mutate(Estimate = ifelse(a == "search" | b == "search", Estimate*-1, Estimate))%>%
  mutate(b = recode(b,
    attent = "ZAttention-following",
    gaze = "ZGaze-following",
    cause = "Causal-inference",
    inference = "Inference-by-exclusion",
    delay = "Delay-of-gratification",
    comm = "ZCommunicative-cues",
    search = "Self-ordered-search",
    pop = "Population-to-sample",
    quant = "Quantity-discrimination",
    reas = "XProbabilistic-reasoning",
    vfood = "Ignore-visible-food"
  ),
  a = recode(a,
    attent = "ZAttention-following",
    gaze = "ZGaze-following",
    cause = "Causal-inference",
    inference = "Inference-by-exclusion",
    delay = "Delay-of-gratification",
    comm = "ZCommunicative-cues",
    search = "Self-ordered-search",
    pop = "Population-to-sample",
    quant = "Quantity-discrimination",
    reas = "XProbabilistic-reasoning",
    vfood = "Ignore-visible-food"
  ))%>%
   rowwise()%>%
  mutate(id = paste(sort(c(b, a)), collapse = "_"))%>%
  separate(id, into = c("task", "task_1"), sep = "_")%>%
  add_row(task_1 = "Ignore-visible-food", task = "Ignore-visible-food", Estimate = 0)%>%
   add_row(task = "ZCommunicative-cues",task_1 = "ZCommunicative-cues", Estimate = 0)%>%
  arrange(task, task_1)%>%
  mutate(
    zero = 0, 
    sig = ifelse(between(zero, `l-95% CI`, `u-95% CI`), "plain", "bold"),
    sig = ifelse(is.na(sig), "plain", sig))%>%
  mutate(order = as.numeric(factor(task)),
         order_1 = as.numeric(factor(task_1)))

saveRDS(pair_cor_mult_bin, "../saves/pair_cor_mult_bin.rds")

pair_cor_mult_bin <- readRDS("../saves/pair_cor_mult_bin.rds")
```

```{r}
p_pair_cor_bin <- pair_cor_mult_bin%>%
  ggplot(aes(y = factor(order), x = factor(order_1), fill = Estimate))+
  geom_tile(color = "white")+
  labs(x = "", y = "")+
  scale_fill_gradient2(low = "#CC6677", high = "#117733", mid = "white", 
  midpoint = 0, limit = c(-1,1), space = "Lab", 
  name="Correlation")+
  ggtitle("brms binomial model")+
  geom_text(aes(label = round(Estimate, 2), fontface = sig), size = 3)+
  scale_y_discrete(breaks = c(1:9),labels = c(str_remove(str_remove(sort(unique(cor_mult_bin$task)), "Z"),"X")))+
  scale_x_discrete(guide = guide_axis(angle = 90), labels = c(str_remove(str_remove(sort(unique(cor_mult_bin$task_1)), "Z"),"X")))+
  #scale_y_discrete(limits=rev, breaks = c(1:10))+
  #scale_x_discrete(breaks = c(1:9))+
  theme_few()+
  theme(legend.position =  c(0.15, 0.8), legend.direction = "vertical", legend.title = element_blank(), legend.background = element_blank())
```
