---
title: "Response to reviewers"
output: html_document
date: "2025-09-30"
---

```{r, include = F}
knitr::opts_chunk$set(echo=F, warning=FALSE, message=FALSE, size="small")

opts <- options(knitr.kable.NA = "")
```

```{r, cache = F, include = F}
library(png)
library(grid)
library(xtable)
library(tidybayes)
library(ggridges)
library(glue)
library(brms)
library(stringr)
library(forcats)
library(ggthemes)
library(ggpubr)
library(reshape)
library(ggExtra)
library(tidybayes)
library(tidyboot)
library(MplusAutomation)
library(kableExtra)
library(knitr)
library(ggstance)
library(magick)
library(pdftools)
library(projpred)
library(bayesplot)
library(loo)
library(directlabels)
library(tidyverse)
library(cowplot)
library(readxl)

source("../utils/custom_facet.R")

cor_func <- function(x) {
  x %>%
    corrr::correlate()%>%
    gather(time_point, cor, -term)%>%
    mutate(cor = replace(cor, duplicated(cor), NA))%>%
    drop_na(cor)
}

library(coda)

estimate_mode <- function(s) {
  d <- density(s)
  return(d$x[which.max(d$y)])
}

hdi_upper<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","upper"])
}

hdi_lower<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","lower"])
}

```

```{r}
# read in data files
data_task <- read.csv("../data/laac2_data_task.csv")%>%
  mutate(task = recode(task,
       "population" = "Population-to-sample",
       "communication" = "Communicative-cues",
       "reasoning" = "Probabilistic-reasoning",
       "visible_food" = "Ignore-visible-food",
       "inhibit_searched" = "Self-ordered-search",
       "attention" = "Attention-following"
  ))

data_trial <- read.csv("../data/laac2_data_trial.csv")%>%
  mutate(task = recode(task,
       "population" = "Population-to-sample",
       "communication" = "Communicative-cues",
       "reasoning" = "Probabilistic-reasoning",
       "visible_food" = "Ignore-visible-food",
       "inhibit_searched" = "Self-ordered-search",
       "attention" = "Attention-following"
  ))
```

```{r }

# Combine datasets from two waves
# --> Restructure_data.R --> saves combined long-format dataset in file "laac_complete.txt"
#long <- read.csv("laac_complete.txt", sep="", na.strings="-99")

long <- read.csv("../data/laac_complete.txt", sep="", na.strings="-99")

# create categorical variables indicating time point and stable trait level
long$trial <- as.factor(long$trial)
long$time_cat <- as.factor(long$time_point)
long$trait <- 1
# recode search task to binary response
long[long$task == "search", "code"] <- car::recode(long[long$task == "search", "code"], '2=1')

long_bin <- long%>%
  filter(!is.na(code))%>%
  group_by(time_point, subject, task, time_cat, trait)%>%
  summarise(n = length(code), 
            sum = sum(code))%>%
  ungroup()

long_bin_all <- long_bin%>%
  mutate(phase = ifelse(task %in% c("cause", "delay", "gaze", "inference", "quant"), 1, 2))%>%
  mutate(time_point = ifelse(phase == 1, time_point - 4, time_point))%>%
  filter(time_point > 0)%>%
  mutate(time_cat = as.factor(time_point))

write_csv(long_bin_all, "../data/data_binomial_modles_combined.csv")

```

# Search patterns self-ordered search

```{r}
search_dat_ind <- read_csv("../data/inhibit_searched_data.csv")%>%
  rowwise()%>%
  mutate(search_pattern = paste0(search_1, search_2, search_3))%>%
  group_by(subject, group,time_point, search_pattern)%>%
  summarise(freq = n())%>%
  group_by(subject, time_point)%>%
  mutate(prop_dominant = freq/sum(freq))%>%
  group_by(subject, time_point)%>%
  filter(prop_dominant == max(prop_dominant))


search_dat_agg <- search_dat_ind%>%
  group_by(time_point)%>%
  tidyboot_mean(column = prop_dominant)

ggplot()+
  geom_point(data =search_dat_ind, aes(x = factor(time_point), y = prop_dominant), alpha = 0.1)+
  geom_line(data =search_dat_ind, aes(x = factor(time_point), y = prop_dominant, group = subject), alpha = 0.1)+
  #geom_point(data =search_dat_agg, aes(x = time_point, y = mean), col = "firebrick")+
  geom_pointrange(data =search_dat_agg, aes(x = time_point, y = mean, ymin = ci_lower, ymax = ci_upper), col = "firebrick")+
  labs(x = "Time point", y = "Proportion most dominant search pattern")+
  geom_line(data =search_dat_agg, aes(x = time_point, y = mean), col = "firebrick")+
  theme_bw()
```
```{r}
search_dat_ind%>%
  ggplot(aes(x=factor(time_point), y = subject, fill = prop_dominant))+
  geom_tile()+
  facet_grid(group~., scales = "free_y", space = "free_y")+
  labs(x = "Time point", y = "Subject")+
  scale_fill_viridis_c()
```

```{r}
ggsave("../visuals/prop_search_ind.png", height = 10, width = 6)
```



```{r}
search_dat_agg_pat <- read_csv("../data/inhibit_searched_data.csv")%>%
  rowwise()%>%
  mutate(search_pattern = paste0(search_1, search_2, search_3))%>%
  mutate(search_pattern = ifelse(search_pattern %in% c("123", "132", "213", "231", "312", "321"), search_pattern, "redunant search"))%>%
  group_by(time_point, search_pattern)%>%
  summarise(n = n())%>%
  group_by(time_point)%>%
  mutate(sum = sum(n))%>%
  rowwise()%>%
  mutate(prop = n/sum)

search_dat_agg_pat%>%
  ggplot(aes(x = search_pattern, y = prop))+
  geom_bar(stat = "identity")+
  facet_grid(time_point~.)+
  theme_bw()

search_dat_agg_pat%>%
  #filter(search_pattern %in% c("123", "132", "213", "231", "312", "321"))%>%
  ggplot(aes(x = factor(time_point), y = prop, col = search_pattern))+
  geom_point()+
  geom_line(aes(group = search_pattern))+
  labs(x = "Time point", y = "Proportion strategy")+
  scale_color_colorblind()+
  theme_bw()
```

# Correlated slopes

```{r}
ds <- long_bin_all%>%mutate(id = paste(subject, task, sep = "_"))

# reference model 
bmr <-  brm(sum|trials(n) ~ time_point,
            data = ds%>%filter(id == unique(ds$id)[1]),
            family = binomial(),
            chains = 3,
            cores = 3,
            iter=2000)

#ind_slopes <- tibble()

for (i in unique(ds$id)) {
  
  dx <- ds%>%filter(id == i)
  
  bmij <- update(bmr, newdata = dx)
  
  x <- summary(bmij)$fixed%>%as_tibble(rownames = "param")%>%filter(param == "time_point")%>%mutate(id = i)
  
  ind_slopes <- bind_rows(ind_slopes, xchains = 3, cores = 3)   
  
  saveRDS(ind_slopes, paste0("../saves/id_slopes.rds"))
  
}

```
```{r}
dslopes <- ind_slopes%>%
  filter(Rhat <2)%>%
  separate(id, into = c("subject", "task"))%>%
  select(Estimate, subject, task)%>%
  pivot_wider(names_from = task, values_from = Estimate)


cor_slopes <- corrr::correlate(dslopes)%>%
    gather(task, cor, -term)%>%
    mutate(cor = replace(cor, duplicated(cor), NA))%>%
    drop_na(cor)%>%
  mutate(b = recode(term,
    attent = "ZAttention-following",
    gaze = "ZGaze-following",
    cause = "Causal-inference",
    inference = "Inference-by-exclusion",
    delay = "Delay-of-gratification",
    comm = "ZCommunicative-cues",
    search = "Self-ordered-search",
    pop = "Population-to-sample",
    quant = "Quantity-discrimination",
    reas = "XProbabilistic-reasoning",
    vfood = "Ignore-visible-food"
  ),
  a = recode(task,
    attent = "ZAttention-following",
    gaze = "ZGaze-following",
    cause = "Causal-inference",
    inference = "Inference-by-exclusion",
    delay = "Delay-of-gratification",
    comm = "ZCommunicative-cues",
    search = "Self-ordered-search",
    pop = "Population-to-sample",
    quant = "Quantity-discrimination",
    reas = "XProbabilistic-reasoning",
    vfood = "Ignore-visible-food"
  ))%>%
   rowwise()%>%
  mutate(id = paste(sort(c(b, a)), collapse = "_"))%>%
  separate(id, into = c("task", "task_1"), sep = "_")%>%
  arrange(task, task_1)%>%
  mutate(order = as.numeric(factor(task)),
         order_1 = as.numeric(factor(task_1)))
```
```{r}
cor_slopes%>%
  ggplot(aes(y = factor(order), x = factor(order_1), fill = cor))+
  geom_tile(color = "white")+
  labs(x = "", y = "")+
  scale_fill_gradient2(low = "#CC6677", high = "#117733", mid = "white", 
  midpoint = 0, limit = c(-1,1), space = "Lab", 
  name="Correlation")+
  ggtitle("Correlations between slopes for time_point")+
  geom_text(aes(label = round(cor, 2)), size = 3)+
  scale_y_discrete(breaks = c(1:10),labels = c(str_remove(str_remove(sort(unique(cor_slopes$task)), "Z"),"X")))+
  scale_x_discrete(guide = guide_axis(angle = 90), labels = c(str_remove(str_remove(sort(unique(cor_slopes$task_1)), "Z"),"X")))+
  #scale_y_discrete(limits=rev, breaks = c(1:10))+
  #scale_x_discrete(breaks = c(1:9))+
  theme_few()+
  theme(legend.position =  c(0.15, 0.8), legend.direction = "vertical", legend.title = element_blank(), legend.background = element_blank())
```

```{r}
ggsave("../visuals/cor_slopes.png", height = 6, width = 8)
```

# Trial 1 data

```{r}
pt1 <- data_trial%>%
  filter(time_point == 1)%>%
  group_by(task, trial)%>%
  tidyboot_mean(col = code)


pt1%>%
  filter(task %in% c("Attention-following", "Communicative-cues"))%>%
  ggplot(aes(x = factor(trial), y = mean, col = task))+
  geom_hline(yintercept = 0.5, lty = 3, alpha = 0.5)+
  geom_line(aes(group = task))+
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper, col = task))+
  theme_bw()+
  facet_grid(task~.)+
  scale_color_colorblind(guide = "none")+
  labs(y = "Proportion correct", x = "Trial (session 1)")+
  ylim(0,1)
```

